### ISSUE TITLE
Bug in ClientTracer::startSpan

### ISSUE THREAD

**Issue by lord2800** [lightstep/lightstep-tracer-php#25]
When passing fields to `ClientTracer::startSpan`, if those fields includes a `tags` key, [`startSpan` attempts to call `ClientSpan::setTags`](https://github.com/lightstep/lightstep-tracer-php/blob/9990c076819baa77d40f0eee58b272048cf61e3e/lib/Client/ClientTracer.php#L230-L232), but that method doesn't exist. What it should probably do instead is `foreach` over the tags and call [`ClientSpan::setTag`](https://github.com/lightstep/lightstep-tracer-php/blob/9990c076819baa77d40f0eee58b272048cf61e3e/lib/Client/ClientSpan.php#L98) with each of the tags.

**Comment by austinlparker** [comment]
@lord2800 can you look at #26 and sanity check me? (not really super familiar with PHP). I think it fixes your issue though.

**Comment by lord2800** [comment]
I left a comment. It's not really clear how `setTags` is supposed to work, so it could go one of two ways. From the usual PHP perspective, one would expect to be able to pass a hash map of keys to values and those would be picked up accordingly, but it's also perfectly viable to treat it as a set of key and value tuples with no loss of meaning. Either way is fine, just requires some documentation.
